wip: helm doc

diff --git a/.github/workflows/doc-helm.yaml b/.github/workflows/doc-helm.yaml
--- a/.github/workflows/doc-helm.yaml
+++ b/.github/workflows/doc-helm.yaml
@@ -8,6 +8,27 @@ jobs:
     - uses: actions/checkout@v4
       with:
         ref: ${{ github.event.pull_request.head.ref }}
+
+    - name: Get the rs-server version tag
+      id: get_version
+      shell: bash
+      run: |
+        # Enable pipefail so git command failures do not result in null versions downstream
+        set -x
+
+        echo "RSSERVER_VERSION=$(\
+            git ls-remote --tags --refs --sort="v:refname" \
+            https://github.com/RS-PYTHON/rs-server.git 'v*.*' | tail -n1 | sed 's/.*\///' | sed 's/^v//' | cut -d '.' -f 1 \
+        )" >> $GITHUB_OUTPUT
+        echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
+
+    - name: Update version number in chart.yaml
+      shell: bash
+      run: |
+        for chart in $(find charts -name Chart.yaml); do
+        sed -i "s,{{CHART_VERSION}},${{ steps.get_version.outputs.RSSERVER_VERSION }}.0.0-${{ steps.get_version.outputs.SHA_SHORT }}," $chart
+        done
+
     - name: Run helm-docs
       uses: losisin/helm-docs-github-action@v1
       with:
